:syntax on
:set number
:set tabstop=2 
:set expandtab    
:set shiftwidth=2 
:set autoindent 
:set smartindent 
:set cursorline
:set nowrap

" colorscheme monokai

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

set nocompatible              " be iMproved, required
filetype off                  " required

" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'kchmck/vim-coffee-script'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-bundler'
Plugin 'wesQ3/vim-windowswap'
Plugin 'tomtom/tcomment_vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'cesardeazevedo/Fx-ColorScheme'
Plugin 'mxw/vim-jsx'
Plugin 'posva/vim-vue'

" All of your Plugins must be added before the following line
call vundle#end()            " required
syntax enable
filetype plugin indent on    " required
" To ignore plugin indent changes, instead use:
"filetype plugin on
"
" Brief help
" :PluginList       - lists configured plugins
" :PluginInstall    - installs plugins; append `!` to update or just :PluginUpdate
" :PluginSearch foo - searches for foo; append `!` to refresh local cache
" :PluginClean      - confirms removal of unused plugins; append `!` to auto-approve removal
"
" see :h vundle for more details or wiki for FAQ
" Put your non-Plugin stuff after this line

set t_Co=256

" Use vim-jsx plugin for js files
let g:jsx_ext_required = 0
